DROP DATABASE trpl;
CREATE DATABASE trpl DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE trpl;

CREATE TABLE review (
	reviewId VARCHAR(36) NOT NULL PRIMARY KEY,
	content BOOL NOT NULL,
	photos BOOL NOT NULL,
	userId VARCHAR(36) NOT NULL,
	placeId VARCHAR(36) NOT NULL,
	createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	INDEX (placeId, createdAt)
);

CREATE TABLE pointLog (
	id INT AUTO_INCREMENT PRIMARY KEY,
	reviewId VARCHAR(36) NOT NULL,
	userId VARCHAR(36) NOT NULL,
	placeId VARCHAR(36) NOT NULL,
  pContent SMALLINT NOT NULL,
  pPhoto SMALLINT NOT NULL,
  pFirst SMALLINT NOT NULL,
	INDEX (userId)
);